# Site settings
# in the templates available like {{ site.myvariable }}.
title: Cross Canada 2019!
email: dave@unicycledave.com 
brand: Dave Cox
headline: Maker, Climber, Long-Distance Unicyclist 
description: > # this means to ignore newlines until "baseurl:"
  Documenting the 2019 journey from one side of Canada to the other by unicycle.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unicycledave.com" # the base hostname & protocol for your site
copyright: 2018 Dave Cox. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 676335

# Contacts
email: dave@unicycledave.com
twitter: '@UnicycleDave'
instagram: '@unicycle-dave'
# phone: +1-800-555-2016

# Tracking
# googleAnalitycsID: UA-83933844-1

